name = "schedule-planner"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "schedule-db"
database_id = "06daa2af-cfa6-4c06-bc76-e798466eb322"
